/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.course.views;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.Date;
import javax.swing.Timer;

import com.course.model.Author;
import com.course.model.MsgBox;
import com.course.model.Util;
import com.course.model.XImage;


public final class MainJFrame extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.initData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbaCongCu = new javax.swing.JToolBar();
        bntDangXuat = new javax.swing.JButton();
        bntThoat = new javax.swing.JButton();
        spt6 = new javax.swing.JToolBar.Separator();
        bntChuyenDe = new javax.swing.JButton();
        bntNguoiHoc = new javax.swing.JButton();
        bntKhoaHoc = new javax.swing.JButton();
        bntHocVien = new javax.swing.JButton();
        spt7 = new javax.swing.JToolBar.Separator();
        bntHuongDan = new javax.swing.JButton();
        pnlTrangThai = new javax.swing.JPanel();
        lblTrangThai = new javax.swing.JLabel();
        lblThoiGian = new javax.swing.JLabel();
        tblAnhLogo = new javax.swing.JLabel();
        mnuBarEduSys = new javax.swing.JMenuBar();
        mnuHeThong = new javax.swing.JMenu();
        mniDoiMatKjau = new javax.swing.JMenuItem();
        spt1 = new javax.swing.JPopupMenu.Separator();
        mniDangXuat = new javax.swing.JMenuItem();
        spt2 = new javax.swing.JPopupMenu.Separator();
        mniKetThuc = new javax.swing.JMenuItem();
        mnuQuanLy = new javax.swing.JMenu();
        mniChuyenDe = new javax.swing.JMenuItem();
        mniKhoaHoc = new javax.swing.JMenuItem();
        mniNguoiHoc = new javax.swing.JMenuItem();
        mniHocVien = new javax.swing.JMenuItem();
        spt3 = new javax.swing.JPopupMenu.Separator();
        mniNhanVien = new javax.swing.JMenuItem();
        mnuThongKe = new javax.swing.JMenu();
        mniBangDiem = new javax.swing.JMenuItem();
        spt4 = new javax.swing.JPopupMenu.Separator();
        mniLuongNguoiHoc = new javax.swing.JMenuItem();
        mniDiemChuyenDe = new javax.swing.JMenuItem();
        mniDoanhThu = new javax.swing.JMenuItem();
        mnuTroGiup = new javax.swing.JMenu();
        mniHuongDan = new javax.swing.JMenuItem();
        spt5 = new javax.swing.JPopupMenu.Separator();
        mniGioiThieu = new javax.swing.JMenuItem();
        spt8 = new javax.swing.JPopupMenu.Separator();
        mniGioiThieu1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HỆ THỐNG QUẢN LÝ ĐÀO TẠO");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(XImage.getIcon("logoFPT.png").getImage());
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        tbaCongCu.setRollover(true);
        tbaCongCu.setAutoscrolls(true);
        tbaCongCu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbaCongCu.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        bntDangXuat.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        bntDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/exit.png"))); // NOI18N
        bntDangXuat.setText("Đăng xuất");
        bntDangXuat.setFocusable(false);
        bntDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bntDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bntDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDangXuatActionPerformed(evt);
            }
        });
        tbaCongCu.add(bntDangXuat);

        bntThoat.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        bntThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/multiply.png"))); // NOI18N
        bntThoat.setText("Thoát");
        bntThoat.setFocusable(false);
        bntThoat.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bntThoat.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bntThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntThoatActionPerformed(evt);
            }
        });
        tbaCongCu.add(bntThoat);
        tbaCongCu.add(spt6);

        bntChuyenDe.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        bntChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/document.png"))); // NOI18N
        bntChuyenDe.setText("Chuyên đề");
        bntChuyenDe.setFocusable(false);
        bntChuyenDe.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bntChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntChuyenDeActionPerformed(evt);
            }
        });
        tbaCongCu.add(bntChuyenDe);

        bntNguoiHoc.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        bntNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/discussion.png"))); // NOI18N
        bntNguoiHoc.setText("Người học");
        bntNguoiHoc.setFocusable(false);
        bntNguoiHoc.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bntNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntNguoiHocActionPerformed(evt);
            }
        });
        tbaCongCu.add(bntNguoiHoc);

        bntKhoaHoc.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        bntKhoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/online-course.png"))); // NOI18N
        bntKhoaHoc.setText("Khóa học");
        bntKhoaHoc.setFocusable(false);
        bntKhoaHoc.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bntKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntKhoaHocActionPerformed(evt);
            }
        });
        tbaCongCu.add(bntKhoaHoc);

        bntHocVien.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        bntHocVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/graduated.png"))); // NOI18N
        bntHocVien.setText("Học viên");
        bntHocVien.setFocusable(false);
        bntHocVien.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bntHocVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntHocVienActionPerformed(evt);
            }
        });
        tbaCongCu.add(bntHocVien);
        tbaCongCu.add(spt7);

        bntHuongDan.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        bntHuongDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/planet-earth.png"))); // NOI18N
        bntHuongDan.setText("Hướng dẫn");
        bntHuongDan.setFocusable(false);
        bntHuongDan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bntHuongDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntHuongDanActionPerformed(evt);
            }
        });
        tbaCongCu.add(bntHuongDan);

        pnlTrangThai.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        lblTrangThai.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblTrangThai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTrangThai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/info.png"))); // NOI18N
        lblTrangThai.setText("Hệ thống quản lý đào tạo");
        lblTrangThai.setToolTipText("");
        lblTrangThai.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblTrangThai.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblThoiGian.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblThoiGian.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblThoiGian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/clock.png"))); // NOI18N
        lblThoiGian.setText("   00 : 00 AM");
        lblThoiGian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThoiGianMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlTrangThaiLayout = new javax.swing.GroupLayout(pnlTrangThai);
        pnlTrangThai.setLayout(pnlTrangThaiLayout);
        pnlTrangThaiLayout.setHorizontalGroup(
            pnlTrangThaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTrangThaiLayout.createSequentialGroup()
                .addComponent(lblTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlTrangThaiLayout.setVerticalGroup(
            pnlTrangThaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTrangThaiLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlTrangThaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        tblAnhLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tblAnhLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/logo.png"))); // NOI18N
        tblAnhLogo.setToolTipText("");
        tblAnhLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblAnhLogo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tblAnhLogo.setOpaque(true);

        mnuBarEduSys.setToolTipText("Hệ thống");
        mnuBarEduSys.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        mnuBarEduSys.setInheritsPopupMenu(true);

        mnuHeThong.setText("Hệ thống");
        mnuHeThong.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N

        mniDoiMatKjau.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        mniDoiMatKjau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/refresh.png"))); // NOI18N
        mniDoiMatKjau.setText("Đổi mật khẩu");
        mniDoiMatKjau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoiMatKjauActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDoiMatKjau);
        mnuHeThong.add(spt1);

        mniDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniDangXuat.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        mniDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/exit.png"))); // NOI18N
        mniDangXuat.setText("Đăng xuất");
        mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDangXuatActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniDangXuat);
        mnuHeThong.add(spt2);

        mniKetThuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        mniKetThuc.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        mniKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/multiply.png"))); // NOI18N
        mniKetThuc.setText("Kết thúc");
        mniKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKetThucActionPerformed(evt);
            }
        });
        mnuHeThong.add(mniKetThuc);

        mnuBarEduSys.add(mnuHeThong);

        mnuQuanLy.setText("Quản lý");
        mnuQuanLy.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N

        mniChuyenDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniChuyenDe.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        mniChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/document.png"))); // NOI18N
        mniChuyenDe.setText("Chuyên đề");
        mniChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniChuyenDeActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniChuyenDe);

        mniKhoaHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniKhoaHoc.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        mniKhoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/online-course.png"))); // NOI18N
        mniKhoaHoc.setText("Khóa học");
        mniKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniKhoaHocActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniKhoaHoc);

        mniNguoiHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniNguoiHoc.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        mniNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/discussion.png"))); // NOI18N
        mniNguoiHoc.setText("Người học");
        mniNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNguoiHocActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniNguoiHoc);

        mniHocVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniHocVien.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        mniHocVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/graduated.png"))); // NOI18N
        mniHocVien.setText("Học viên");
        mniHocVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHocVienActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniHocVien);
        mnuQuanLy.add(spt3);

        mniNhanVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mniNhanVien.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        mniNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/service.png"))); // NOI18N
        mniNhanVien.setText("Nhân viên");
        mniNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNhanVienActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mniNhanVien);

        mnuBarEduSys.add(mnuQuanLy);

        mnuThongKe.setText("Thống kê");
        mnuThongKe.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N

        mniBangDiem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniBangDiem.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        mniBangDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/score.png"))); // NOI18N
        mniBangDiem.setText("Bảng điểm");
        mniBangDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniBangDiemActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniBangDiem);
        mnuThongKe.add(spt4);

        mniLuongNguoiHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniLuongNguoiHoc.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        mniLuongNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/customer.png"))); // NOI18N
        mniLuongNguoiHoc.setText("Lượng người học");
        mniLuongNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLuongNguoiHocActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniLuongNguoiHoc);

        mniDiemChuyenDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniDiemChuyenDe.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        mniDiemChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/bar-chart.png"))); // NOI18N
        mniDiemChuyenDe.setText("Điểm chuyên đề");
        mniDiemChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDiemChuyenDeActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniDiemChuyenDe);

        mniDoanhThu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mniDoanhThu.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        mniDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/income.png"))); // NOI18N
        mniDoanhThu.setText("Doanh thu");
        mniDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniDoanhThuActionPerformed(evt);
            }
        });
        mnuThongKe.add(mniDoanhThu);

        mnuBarEduSys.add(mnuThongKe);

        mnuTroGiup.setText("Trợ giúp");
        mnuTroGiup.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N

        mniHuongDan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mniHuongDan.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        mniHuongDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/planet-earth.png"))); // NOI18N
        mniHuongDan.setText("Hướng dẫn sử dụng");
        mniHuongDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHuongDanActionPerformed(evt);
            }
        });
        mnuTroGiup.add(mniHuongDan);
        mnuTroGiup.add(spt5);

        mniGioiThieu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        mniGioiThieu.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        mniGioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/product.png"))); // NOI18N
        mniGioiThieu.setText("Giới thiệu sản phẩm");
        mniGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGioiThieuActionPerformed(evt);
            }
        });
        mnuTroGiup.add(mniGioiThieu);
        mnuTroGiup.add(spt8);

        mniGioiThieu1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        mniGioiThieu1.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        mniGioiThieu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/send.png"))); // NOI18N
        mniGioiThieu1.setText("Gửi thông tin email");
        mniGioiThieu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniGioiThieu1ActionPerformed(evt);
            }
        });
        mnuTroGiup.add(mniGioiThieu1);

        mnuBarEduSys.add(mnuTroGiup);

        setJMenuBar(mnuBarEduSys);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbaCongCu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 710, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTrangThai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tblAnhLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tbaCongCu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tblAnhLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniDoiMatKjauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoiMatKjauActionPerformed
        DoiMatKhauJDialog dialog = new DoiMatKhauJDialog(this, true);
        this.lblTrangThai.setText(dialog.getTitle());
        dialog.setVisible(true);
    }//GEN-LAST:event_mniDoiMatKjauActionPerformed

    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
        this.dispose();
        new DangNhapJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_mniDangXuatActionPerformed

    private void mniKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKetThucActionPerformed
        this.ExitForm(this.getTitle());
    }//GEN-LAST:event_mniKetThucActionPerformed

    private void mniChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniChuyenDeActionPerformed
        this.setForm(new ChuyenDeJFrame(this));
    }//GEN-LAST:event_mniChuyenDeActionPerformed

    private void mniKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniKhoaHocActionPerformed
        this.setForm(new KhoaHocJFrame(this));
    }//GEN-LAST:event_mniKhoaHocActionPerformed

    private void mniNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNguoiHocActionPerformed
        this.setForm(new NguoiHocJFrame(this));
    }//GEN-LAST:event_mniNguoiHocActionPerformed

    private void mniHocVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHocVienActionPerformed
        this.setForm(new HocVienJFrame(this));
    }//GEN-LAST:event_mniHocVienActionPerformed

    private void mniNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNhanVienActionPerformed
        this.setForm(new NhanVienJFrame(this));
    }//GEN-LAST:event_mniNhanVienActionPerformed

    private void mniBangDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniBangDiemActionPerformed
        this.ThongKeSelected(0); // "0" vị trí mặc định
    }//GEN-LAST:event_mniBangDiemActionPerformed

    private void mniLuongNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLuongNguoiHocActionPerformed
        this.ThongKeSelected(1); // "1" vị trí người học
    }//GEN-LAST:event_mniLuongNguoiHocActionPerformed

    private void mniDiemChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDiemChuyenDeActionPerformed
        this.ThongKeSelected(2); // "2" vị trí chuyên đề
    }//GEN-LAST:event_mniDiemChuyenDeActionPerformed

    private void mniDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoanhThuActionPerformed
        if (Author.isManager()) {
            this.ThongKeSelected(3); // "3" vị trí doanh thu
        } else
            MsgBox.alert(this, "Tính năng chưa dành cho nhân viên!",
                    "Quyền truy cập", MsgBox.ThongTin);
    }//GEN-LAST:event_mniDoanhThuActionPerformed

    private void mniHuongDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHuongDanActionPerformed
        this.lblTrangThai.setText("Hướng dẫn ứng dụng!");
        this.openWebSide("help/index.html", "Hướng dẫn.");
    }//GEN-LAST:event_mniHuongDanActionPerformed

    private void mniGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGioiThieuActionPerformed
        this.lblTrangThai.setText("Giới thiệu sản phẩm!");
        this.openWebSide("help/products.html", "Hướng dẫn.");
    }//GEN-LAST:event_mniGioiThieuActionPerformed

    private void bntDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDangXuatActionPerformed
        Author.clear();
        this.dispose(); // Đóng cửa sổ hiện tại
        new DangNhapJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_bntDangXuatActionPerformed

    private void bntThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntThoatActionPerformed
        this.ExitForm(this.getTitle());
    }//GEN-LAST:event_bntThoatActionPerformed

    private void bntChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntChuyenDeActionPerformed
        this.setForm(new ChuyenDeJFrame(this));
    }//GEN-LAST:event_bntChuyenDeActionPerformed

    private void bntNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntNguoiHocActionPerformed
        this.setForm(new NguoiHocJFrame(this));
    }//GEN-LAST:event_bntNguoiHocActionPerformed

    private void bntKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntKhoaHocActionPerformed
        this.setForm(new KhoaHocJFrame(this));
    }//GEN-LAST:event_bntKhoaHocActionPerformed

    private void bntHocVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntHocVienActionPerformed
        this.setForm(new HocVienJFrame(this));
    }//GEN-LAST:event_bntHocVienActionPerformed

    private void bntHuongDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntHuongDanActionPerformed
        this.lblTrangThai.setText("Hướng dẫn ứng dụng!");
        this.openWebSide("help/index.html", "Hướng dẫn.");
    }//GEN-LAST:event_bntHuongDanActionPerformed

    private void lblThoiGianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThoiGianMouseClicked
        if (timer.isRunning()) {
            timer.stop();
            this.lblTrangThai.setText("Clock time is stopping: " + new Date(evt.getWhen()));
        } else {
            timer.start();
            this.lblTrangThai.setText("Continue times..." + new Date(evt.getWhen()));
        }
    }//GEN-LAST:event_lblThoiGianMouseClicked

    private void mniGioiThieu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniGioiThieu1ActionPerformed
        MailSendingJDialog dialog = new MailSendingJDialog(this, true);
        this.lblTrangThai.setText(dialog.getTitle());
        dialog.setVisible(true);
    }//GEN-LAST:event_mniGioiThieu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        ChaoJDialog dialog = new ChaoJDialog(new MainJFrame(), true);
        new Thread(dialog).start();
        dialog.setVisible(true);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DangNhapJDialog(new MainJFrame(), true).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntChuyenDe;
    private javax.swing.JButton bntDangXuat;
    private javax.swing.JButton bntHocVien;
    private javax.swing.JButton bntHuongDan;
    private javax.swing.JButton bntKhoaHoc;
    private javax.swing.JButton bntNguoiHoc;
    private javax.swing.JButton bntThoat;
    private javax.swing.JLabel lblThoiGian;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JMenuItem mniBangDiem;
    private javax.swing.JMenuItem mniChuyenDe;
    private javax.swing.JMenuItem mniDangXuat;
    private javax.swing.JMenuItem mniDiemChuyenDe;
    private javax.swing.JMenuItem mniDoanhThu;
    private javax.swing.JMenuItem mniDoiMatKjau;
    private javax.swing.JMenuItem mniGioiThieu;
    private javax.swing.JMenuItem mniGioiThieu1;
    private javax.swing.JMenuItem mniHocVien;
    private javax.swing.JMenuItem mniHuongDan;
    private javax.swing.JMenuItem mniKetThuc;
    private javax.swing.JMenuItem mniKhoaHoc;
    private javax.swing.JMenuItem mniLuongNguoiHoc;
    private javax.swing.JMenuItem mniNguoiHoc;
    private javax.swing.JMenuItem mniNhanVien;
    private javax.swing.JMenuBar mnuBarEduSys;
    private javax.swing.JMenu mnuHeThong;
    private javax.swing.JMenu mnuQuanLy;
    private javax.swing.JMenu mnuThongKe;
    private javax.swing.JMenu mnuTroGiup;
    private javax.swing.JPanel pnlTrangThai;
    private javax.swing.JPopupMenu.Separator spt1;
    private javax.swing.JPopupMenu.Separator spt2;
    private javax.swing.JPopupMenu.Separator spt3;
    private javax.swing.JPopupMenu.Separator spt4;
    private javax.swing.JPopupMenu.Separator spt5;
    private javax.swing.JToolBar.Separator spt6;
    private javax.swing.JToolBar.Separator spt7;
    private javax.swing.JPopupMenu.Separator spt8;
    private javax.swing.JToolBar tbaCongCu;
    private javax.swing.JLabel tblAnhLogo;
    // End of variables declaration//GEN-END:variables

    private Timer timer = null;

    private void initData() {
        timer = Util.setTimer(lblThoiGian, "hh:mm:ss aa");
        timer.start();
        this.setLocationRelativeTo(null);
        this.toFront();
    }

    // Thoát chương trình đăng hiện tại
    public void ExitForm(String title) {
        // MsgBox trả về "0":có - "1":không
        if (MsgBox.confirm(this, "Thoát chương trình \""
                + title + "\"?", title, MsgBox.CanhBao) == 0) {
            System.exit(0);
        }
    }

    private void ThongKeSelected(int table) {
        ThongKeJFrame thongKe = new ThongKeJFrame(this);
        thongKe.getTabsTHTK().setSelectedIndex(table);
        this.setForm(thongKe);
    }

    private void setForm(javax.swing.JFrame frame) {
        frame.setVisible(rootPaneCheckingEnabled);
        frame.setFocusCycleRoot(rootPaneCheckingEnabled);
        frame.doLayout();
        this.lblTrangThai.setText(frame.getTitle());
    }

    private void openWebSide(String path, String mes) {
        try {
            Desktop.getDesktop().browse(new File(path).toURI());
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
            MsgBox.alert(this, "Không tìm thấy trang!", mes, MsgBox.KhongCo);
        }
    }
}
