/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.course.views;

import java.util.Date;

import com.course.dao.NhanVienDAO;
import com.course.entites.NhanVien;
import com.course.model.Author;
import com.course.model.MsgBox;
import com.course.model.SendMail;
import com.course.model.Util;
import com.course.model.Validate;

/**
 *
 * @author abc
 */
public final class QuenMatKhauJDialog extends javax.swing.JDialog {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form QuenMatKhauJDialog
     *
     * @param parent
     * @param modal
     */
    java.awt.Frame parent;

    public QuenMatKhauJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMaNV = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblAnh = new javax.swing.JLabel();
        lblXacThuc = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtXacThuc = new javax.swing.JTextField();
        bntDongY = new javax.swing.JButton();
        bntLayMa = new javax.swing.JButton();
        bntHuyBo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quên mật khảu");

        lblMaNV.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblMaNV.setText("Tên đăng nhập");

        lblEmail.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        lblEmail.setText("Email nhân viên");

        lblAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/Poly.png"))); // NOI18N
        lblAnh.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblXacThuc.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblXacThuc.setText("MÃ XÁC THỰC EMAIL");

        txtMaNV.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        txtXacThuc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtXacThuc.setForeground(new java.awt.Color(255, 0, 0));

        bntDongY.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        bntDongY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/refresh.png"))); // NOI18N
        bntDongY.setText("Đồng ý");
        bntDongY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDongYActionPerformed(evt);
            }
        });

        bntLayMa.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        bntLayMa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/send.png"))); // NOI18N
        bntLayMa.setText("Lấy mã");
        bntLayMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntLayMaActionPerformed(evt);
            }
        });

        bntHuyBo.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        bntHuyBo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/icons/multiply.png"))); // NOI18N
        bntHuyBo.setText("Hủy bỏ");
        bntHuyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntHuyBoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bntDongY)
                        .addGap(18, 18, 18)
                        .addComponent(bntLayMa)
                        .addGap(18, 18, 18)
                        .addComponent(bntHuyBo))
                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaNV)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblXacThuc)
                        .addGap(18, 18, 18)
                        .addComponent(txtXacThuc)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bntDongY, bntHuyBo, bntLayMa});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtXacThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblXacThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bntHuyBo)
                            .addComponent(bntLayMa)
                            .addComponent(bntDongY))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntLayMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntLayMaActionPerformed
        this.getCodeMail();
    }//GEN-LAST:event_bntLayMaActionPerformed

    private void bntHuyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntHuyBoActionPerformed
        Author.user = null;
        this.dispose();
    }//GEN-LAST:event_bntHuyBoActionPerformed

    private void bntDongYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDongYActionPerformed
        NhanVienDAO dao = new NhanVienDAO();
        String code = txtMaNV.getText();
        NhanVien x = dao.SelectById(code == null ? "" : code);
        if (XacNhan(x) != null) {
            if (dao.Update(x)) {
                Author.user = x;
                MsgBox.alert(this, "Đã cập nhật thông tin của bạn",
                        "Cập nhật thành công", MsgBox.ThongTin);
                this.dispose();
            }
        } else {
            MsgBox.alert(this, "Không thể lấy lại mật khẩu này",
                    "Cập nhật thất bại", MsgBox.CanhBao);
            txtXacThuc.setText(null);
        }
    }//GEN-LAST:event_bntDongYActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            QuenMatKhauJDialog dialog = new QuenMatKhauJDialog(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntDongY;
    private javax.swing.JButton bntHuyBo;
    private javax.swing.JButton bntLayMa;
    private javax.swing.JLabel lblAnh;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblXacThuc;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtXacThuc;
    // End of variables declaration//GEN-END:variables

    String Code = Util.ramdomCode(5);
    private int count = 0;

    private NhanVien XacNhan(NhanVien x) {
        if (count == 5) { // Cho phép nhập tối đa 5 lần
            this.dispose();
        }
        ++count;
        if (x != null) {
            boolean MaNV = x.getMaNV().equalsIgnoreCase(txtMaNV.getText());
            boolean check = txtXacThuc.getText().equals(Code);
            String pass, pass2 = "";
            if (!check) {
                MsgBox.alert(this, "Mã xác thực không đúng!", "Xác thực tài khoản", MsgBox.CanhBao);
                return null;
            }
            if (MaNV && check) {

                do {
                    // Lấy mật khẩu lần 1
                    pass = MsgBox.prompt(this, "Nhập mật khẩu mới", "Bước 2: Mật khẩu?", MsgBox.ThongTin);
                    if (pass == null) {
                        return null;
                    }
                    check = Validate.ValString(this, Validate.MAT_KHAU, pass, 5, 50);
                } while (!check);
                while (!pass2.equals(pass)) {
                    // Xác nhận lại mạt khẩu
                    pass2 = MsgBox.prompt(this, "Nhập lại mật khẩu", "Bước 3: Mật khẩu?", MsgBox.ThongTin);
                    if (pass2 == null) {
                        return null;
                    }
                }
                // Sửa mạt khẩu sau hoàn thành
                x.setMatKhau(pass2);
            } else {
                MsgBox.alert(this, "Thông tin của bạn không đúng!",
                        "Sai thông tin", MsgBox.BaoLoi);
                return null;
            }
        } else {
            this.txtMaNV.setText(null);
        }
        return x;
    }

    @SuppressWarnings("deprecation") // Nội dung email cần gửi
    private String createMesage() {
        StringBuilder s = new StringBuilder();
        Date date = new Date();
        s.append("Chào bạn, Lập trình City nhận được yêu cầu cung cấp mã");
        s.append("\nThời gian: ").append(date.getHours()).append("giờ - ");
        s.append(date.getMinutes());
        s.append("phút - ").append(date.getSeconds()).append("giây.");
        s.append("\nMã người dùng là: ").append(txtMaNV.getText());
        s.append("\nMã xác thực tài khoản của bạn là: ").append(Code);
        s.append("\n#Lưu ý: mã xác thực phân biệt hoa và thường");
        s.append("\nXin Cảm ơn!");
        return s.toString();
    }

    // Lấy thông tin mã xác thực
    private void getCodeMail() {
        this.Code = Util.ramdomCode(6);
        NhanVien x = new NhanVienDAO().SelectById(txtMaNV.getText());

        if (x != null) {
            if (!x.getEmail().equalsIgnoreCase(txtEmail.getText())) {
                MsgBox.alert(this, "Không đúng email người dùng",
                        "Lấy mã xác thực email", MsgBox.CanhBao);
            } else {
                SendMail send = new SendMail("Hoandps18107@gmail.com", "Dhps18107");
                String message = this.createMesage();
                send.setUp(txtEmail.getText(), "Mã xác thực tài khoản", message);
                new Thread() {
                    // Tạo tiến trình gửi thông tin mail
                    private final WaitingSendJdialog dialog = new WaitingSendJdialog(parent, true);

                    @Override
                    public void run() {
                        this.createPrg();
                        dialog.setTrangThai("Đang lấy thông tin mã", 30);
                        try {
                            sleep(1000);
                        } catch (InterruptedException e) {
                        }
                        dialog.setTrangThai("Lấy thông tin hoàn thành", 50);
                        this.sending();

                    }

                    // Gửi thông tin mã xác thực tới người dùng
                    private void sending() {
                        dialog.setTrangThai("Đang gửi thông tin email", 70);
                        if (send.sendingEmail()) {
                            dialog.setTrangThai("Đã gửi thông tin email", 100);
                            dialog.dispose();
                            MsgBox.alert(parent, "Mã xác thực được gửi tới: " + x.getEmail(),
                                    "Lấy mã", MsgBox.ThongTin);
                        } else {
                            dialog.setTrangThai("Gửi thông tin email thất bại", 0);
                            dialog.dispose();
                        }
                    }

                    // tọa mới Jdialog thông báo tiến trình
                    private void createPrg() {
                        java.awt.EventQueue.invokeLater(() -> {
                            dialog.setVisible(true);
                        });
                    }
                }.start();
            }
        } else {
            MsgBox.alert(this, "Thông tin không đúng.\nMã người dùng: "
                    + txtMaNV.getText() + " không tồn tại!",
                    "Lấy mã xác thực", MsgBox.CanhBao);
        }
    }
}
