/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.course.views;

/**
 *
 * @author abc
 */
public final class WaitingSendJdialog extends javax.swing.JDialog{

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form WaitingToSending
     *
     * @param parent
     * @param modal
     */
    public WaitingSendJdialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTrangThai = new javax.swing.JLabel();
        pgrTienTrinh = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        lblTrangThai.setFont(new java.awt.Font("Cambria", 2, 18)); // NOI18N
        lblTrangThai.setText("Trạng thái: ...");
        lblTrangThai.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pgrTienTrinh.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        pgrTienTrinh.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pgrTienTrinh.setIndeterminate(true);
        pgrTienTrinh.setStringPainted(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pgrTienTrinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTrangThai, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pgrTienTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JProgressBar pgrTienTrinh;
    // End of variables declaration//GEN-END:variables

    String trangThai; int tienTrinh;
    public void setTrangThai(String trangThai, int tienTrinh) {
        lblTrangThai.setText(this.trangThai = trangThai);
        pgrTienTrinh.setValue(pgrTienTrinh.getValue() < tienTrinh
                ? this.tienTrinh = tienTrinh : pgrTienTrinh.getValue());
    }
}
